// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxNXkv9qMmfKvaKHT91mBTr6TZvcz7aFs',
    appId: '1:685203332796:web:cc65a6e1e3a51da6623ab9',
    messagingSenderId: '685203332796',
    projectId: 'my-chat-fa34b',
    authDomain: 'my-chat-fa34b.firebaseapp.com',
    storageBucket: 'my-chat-fa34b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB50_8dbnYsU7EoQwzdnztFEaqLXFdNDQ0',
    appId: '1:685203332796:android:7d72283cfd0d7d6f623ab9',
    messagingSenderId: '685203332796',
    projectId: 'my-chat-fa34b',
    storageBucket: 'my-chat-fa34b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdNWMAHIGgYGx6bFxFoDloH7oQHkyaLPA',
    appId: '1:685203332796:ios:d15d8085c95fd62e623ab9',
    messagingSenderId: '685203332796',
    projectId: 'my-chat-fa34b',
    storageBucket: 'my-chat-fa34b.appspot.com',
    androidClientId: '685203332796-17ndt4eq4iqhsai4cprjaar0ks16rrkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdNWMAHIGgYGx6bFxFoDloH7oQHkyaLPA',
    appId: '1:685203332796:ios:684b8a7ba7ee2305623ab9',
    messagingSenderId: '685203332796',
    projectId: 'my-chat-fa34b',
    storageBucket: 'my-chat-fa34b.appspot.com',
    androidClientId: '685203332796-17ndt4eq4iqhsai4cprjaar0ks16rrkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitChat.RunnerTests',
  );
}
